Repository CrowdStrike/ansible_collection_falcon, pull requests merged in 2023-09, with the labels that each got.

#397 Molecule updates devel branch
  .github/workflows/falcon_configure.yml
  .github/workflows/falcon_install.yml
  .github/workflows/falcon_uninstall.yml
  .github/workflows/win_falcon_configure.yml
  .github/workflows/win_falcon_install.yml
  .github/workflows/win_falcon_uninstall.yml
  molecule/falcon_configure/molecule.yml
  molecule/falcon_configure/prepare.yml
  molecule/falcon_install/converge.yml
  molecule/falcon_install/molecule.yml
  molecule/falcon_install/prepare.yml
  molecule/falcon_install_allow_downgrade/converge.yml
  molecule/falcon_install_allow_downgrade/molecule.yml
  molecule/falcon_install_allow_downgrade/prepare.yml
  molecule/falcon_install_policy/converge.yml
  molecule/falcon_install_policy/molecule.yml
  molecule/falcon_install_policy/prepare.yml
  molecule/falcon_uninstall/molecule.yml
  molecule/falcon_uninstall/prepare.yml
  molecule/win_falcon_configure/molecule.yml
  molecule/win_falcon_configure/prepare.yml
  molecule/win_falcon_install/molecule.yml
  molecule/win_falcon_install_policy/molecule.yml
Labels: bugfixes, ci/cd, devel

#402 Prep changes for next v3 release
  roles/falcon_configure/README.md
  roles/falcon_configure/tasks/configure.yml
  roles/falcon_install/README.md
  roles/falcon_install/defaults/main.yml
  roles/falcon_uninstall/README.md
Labels: documentation, enhancement, new_release

#399 Host hide module + doc updates
  README.md
  plugins/doc_fragments/credentials.py
  plugins/doc_fragments/info.py
  plugins/modules/host_hide.py
  roles/falcon_configure/README.md
  roles/falcon_configure/tasks/configure.yml
  roles/falcon_install/README.md
  roles/falcon_uninstall/README.md
  roles/falcon_uninstall/defaults/main.yml
  roles/falcon_uninstall/tasks/hide_host.yml
  roles/falcon_uninstall/tasks/main.yml
Labels: documentation, enhancement, minor_changes, devel

#400 discover dynamic inventory
  README.md
  plugins/inventory/falcon_discover.py
Labels: documentation, minor_changes, devel

#403 Bump v3.3.2
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/fix-become-issue-aid.yml
  changelogs/fragments/remove-host.yml
  galaxy.yml
Labels: new_release, v3

#405 chore: update min ansible-core due to 2.12 EOL
  README.md
  meta/runtime.yml
  roles/falcon_configure/README.md
  roles/falcon_install/README.md
  roles/falcon_uninstall/README.md
Labels: documentation, new_release, v3

#407 Bump v3.3.3
  CHANGELOG.rst
  changelogs/changelog.yaml
  galaxy.yml
Labels: new_release, v3

#406 Devel pre release updates
  CHANGELOG.rst
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/fix-become-issue-aid.yml
  changelogs/fragments/remove-host.yml
  changelogs/fragments/sensor-policy-info.yml
  changelogs/fragments/v4-updates.yml
  docs/authentication.md
  galaxy.yml
  inventory.yml
  meta/runtime.yml
  roles/falcon_configure/README.md
  roles/falcon_install/README.md
  roles/falcon_uninstall/README.md
Labels: devel

#409 Bump v4.0.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/v4-updates.yml
Labels: new_release

#411 Host contain module
  README.md
  changelogs/fragments/host_contain.yml
  plugins/modules/host_contain.py
Labels: enhancement, minor_changes, new_release

#412 Bump v4.1.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/host_contain.yml
  galaxy.yml
Labels: new_release

#413 fix(falcon_discover): fixed issue with compose
  changelogs/fragments/discover-fix.yml
  plugins/inventory/falcon_discover.py
  plugins/modules/sensor_download_info.py
Labels: bugfixes, documentation

#414 Bump v4.1.1
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/discover-fix.yml
  galaxy.yml
Labels: new_release

#415 fix eu-1 url
  changelogs/fragments/fix-eu-mapping.yml
  plugins/module_utils/falconpy_utils.py
Labels: bugfixes

#416 Bump v4.1.2
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/fix-eu-mapping.yml
  galaxy.yml
Labels: new_release

#418 fix(falcon_configure): updates auth task for role
  changelogs/fix-configure-role.yml
  roles/falcon_configure/tasks/main.yml
Labels: bugfixes

#419 Bump v4.1.3
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fix-configure-role.yml
  galaxy.yml
Labels: new_release
