Repository CrowdStrike/ansible_collection_falcon, pull requests merged in 2023-02, with the labels that each got.

#291 Ensure plays are named - per ansible-lint
  roles/falcon_configure/tests/test.yml
  roles/falcon_uninstall/tests/test.yml
  tests/test.yml
Labels: ok-to-test

#295 Add retry to build/install step. Refactored falcon_install ci
  .github/workflows/falcon_configure.yml
  .github/workflows/falcon_install.yml
  .github/workflows/falcon_install_policy.yml
  .github/workflows/falcon_uninstall.yml
  .github/workflows/win_falcon_configure.yml
  .github/workflows/win_falcon_install.yml
  .github/workflows/win_falcon_install_policy.yml
  .github/workflows/win_falcon_uninstall.yml
Labels: enhancement, ci/cd

#299 Update ansible facts to use dictionary as opposed to magic name
  molecule/falcon_configure/prepare.yml
  molecule/falcon_install/prepare.yml
  molecule/falcon_install_policy/prepare.yml
  molecule/falcon_uninstall/prepare.yml
  roles/falcon_configure/tasks/configure.yml
  roles/falcon_configure/tasks/main.yml
  roles/falcon_install/tasks/api.yml
  roles/falcon_install/tasks/auth.yml
  roles/falcon_install/tasks/install.yml
  roles/falcon_install/tasks/main.yml
  roles/falcon_install/tasks/preinstall.yml
  roles/falcon_install/tasks/win_install.yml
  roles/falcon_uninstall/tasks/main.yml
  roles/falcon_uninstall/tasks/uninstall.yml
  roles/falcon_uninstall/tasks/win_uninstall.yml
Labels: enhancement, ok-to-test, minor_changes

#302 Use new 2.11.x format to update lint syntax
  meta/runtime.yml
Labels: linting

#306 Fix delegate_to and potential omit bug
  roles/falcon_install/tasks/auth.yml
Labels: bugfixes, ok-to-test, minor_changes

#308 README.md typo fix
  roles/falcon_install/README.md
Labels: documentation
