Repository CrowdStrike/ansible_collection_falcon, pull requests merged in 2023-08, with the labels that each got.

#322 Add EDA event stream source
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/requirements.txt
  .gitignore
  changelogs/fragments/eda.yml
  inventory.yml
  plugins/event_source/eventstream.py
  requirements.txt
  rulebooks/event_stream_example.yml
Labels: enhancement, minor_changes, new_release

#375 Fix bug with using incorrect temp path for windows
  changelogs/fragments/fix-windows-dest-url.yml
  roles/falcon_install/tasks/win_url.yml
Labels: bugfixes, ok-to-test, new_release

#376 Eda announcement updates
  README.md
  docs/crowdstrike.falcon.eventstream.md
  extensions/eda/plugins/event_source/eventstream.py
  extensions/eda/rulebooks/event_stream_example.yml
Labels: documentation, new_release

#377 Bump 3.3.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/eda.yml
  changelogs/fragments/fix-windows-dest-url.yml
  galaxy.yml
Labels: new_release

#381 Eda partner testing
  .devcontainer/requirements.txt
  .pylintrc
  extensions/eda/plugins/event_source/eventstream.py
  galaxy.yml
  meta/extensions.yml
  tox.ini
Labels: linting

#386 bump 3.3.1
  CHANGELOG.rst
  changelogs/changelog.yaml
  galaxy.yml
Labels: new_release

#384 FalconPy 1.3 Scaffolding
  .devcontainer/requirements.txt
  .gitignore
  plugins/doc_fragments/credentials.py
  plugins/module_utils/args_common.py
  plugins/module_utils/falconpy_utils.py
  plugins/module_utils/version.py
  plugins/modules/auth.py
  plugins/modules/sensor_update_policy_info.py
  requirements.txt
  tests/config.yml
  tests/module-test.yml
Labels: enhancement, minor_changes, new_release, devel

#391 Update README to reflect proper ansible version support
  README.md
Labels: documentation

#392 Fix issue with remove aid not having become clause
  changelogs/fragments/fix-become-issue-aid.yml
  roles/falcon_configure/tasks/main.yml
Labels: bugfixes, new_release

#394 Plugins cleanup linting
  README.md
  plugins/module_utils/falconctl_utils.py
  plugins/modules/falconctl.py
  plugins/modules/falconctl_info.py
Labels: documentation, linting, devel

#395 Cid info module
  README.md
  plugins/module_utils/common_args.py
  plugins/module_utils/version.py
  plugins/modules/auth.py
  plugins/modules/cid_info.py
  plugins/modules/sensor_update_policy_info.py
Labels: minor_changes, devel

#393 Add remove/hide host ability for uninstall
  changelogs/fragments/remove-host.yml
  molecule/falcon_uninstall/converge.yml
  molecule/falcon_uninstall/prepare.yml
  molecule/win_falcon_uninstall/converge.yml
  molecule/win_falcon_uninstall/verify.yml
  roles/falcon_uninstall/README.md
  roles/falcon_uninstall/defaults/main.yml
  roles/falcon_uninstall/tasks/hide_host.yml
  roles/falcon_uninstall/tasks/main.yml
  roles/falcon_uninstall/tasks/preuninstall.yml
  roles/falcon_uninstall/tasks/remove_host_pretasks.yml
  roles/falcon_uninstall/tasks/win_uninstall.yml
  roles/falcon_uninstall/vars/main.yml
Labels: ok-to-test, minor_changes, new_release
