Repository CrowdStrike/ansible_collection_falcon, pull requests merged in 2023-07, with the labels that each got.

#365 Minor molecule updates
  .github/workflows/falcon_configure.yml
  .github/workflows/falcon_install.yml
  .github/workflows/falcon_uninstall.yml
  .github/workflows/win_falcon_configure.yml
  .github/workflows/win_falcon_install.yml
  .github/workflows/win_falcon_uninstall.yml
  molecule/falcon_configure/molecule.yml
  molecule/falcon_install/molecule.yml
  molecule/falcon_install_allow_downgrade/molecule.yml
  molecule/falcon_install_policy/molecule.yml
  molecule/falcon_uninstall/molecule.yml
  molecule/shared/playbooks/win_create.yml
  molecule/win_falcon_configure/molecule.yml
  molecule/win_falcon_install/converge.yml
  molecule/win_falcon_install/molecule.yml
  molecule/win_falcon_install_policy/converge.yml
  molecule/win_falcon_install_policy/molecule.yml
  molecule/win_falcon_uninstall/molecule.yml
  molecule/win_falcon_uninstall/prepare.yml
Labels: enhancement, ok-to-test, ci/cd

#366 Remove double quote messing up molecule test
  .github/workflows/win_falcon_configure.yml
  .github/workflows/win_falcon_install.yml
  .github/workflows/win_falcon_uninstall.yml
Labels: bugfixes, ci/cd

#364 falcon_install - add the ability to install from an url link for windows
  changelogs/fragments/url_ability_for_windows.yml
  roles/falcon_install/tasks/main.yml
  roles/falcon_install/tasks/win_url.yml
Labels: enhancement, ok-to-test, minor_changes

#367 Removed kernel compat due to prevelance of ebpf support
  .github/workflows/falcon_configure.yml
  .github/workflows/falcon_install.yml
  .github/workflows/falcon_uninstall.yml
  changelogs/fragments/remove-kernel-compat.yml
  roles/falcon_install/README.md
  roles/falcon_install/defaults/main.yml
  roles/falcon_install/tasks/api.yml
Labels: minor_changes

#369 Updates to devcontainer
  .devcontainer/Dockerfile
  .devcontainer/README.md
  .devcontainer/devcontainer.json
  .devcontainer/library-scripts/common-debian.sh
  .devcontainer/library-scripts/docker-in-docker-debian.sh
  .devcontainer/requirements.txt
Labels: enhancement

#368 dest should follow same convention as linux
  changelogs/fragments/url_ability_for_windows.yml
  roles/falcon_install/tasks/win_url.yml
Labels: bugfixes

#371 bump 3.2.36
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/remove-kernel-compat.yml
  changelogs/fragments/url_ability_for_windows.yml
  galaxy.yml
Labels: new_release
