Repository CrowdStrike/ansible_collection_falcon, pull requests merged in 2024-03, with the labels that each got.

#459 chore: update falconpy + clean up docs
  .devcontainer/requirements.txt
  README.md
  requirements.txt
Labels: documentation, dependencies

#462 chore: update python linting for modules
  .flake8
  .pylintrc
  plugins/inventory/falcon_discover.py
  plugins/modules/sensor_download.py
Labels: linting, ci/cd

#463 V3 lint updates
  .flake8
  .pylintrc
  extensions/eda/plugins/event_source/eventstream.py
  tox.ini
Labels: linting

#464 Bump 3.3.4
  CHANGELOG.rst
  changelogs/changelog.yaml
  extensions/eda/plugins/event_source/eventstream.py
  galaxy.yml
Labels: new_release

#466 chore: update falcon-configure molecule
  molecule/falcon_configure/converge.yml
  molecule/falcon_configure/verify.yml
Labels: bugfixes, ci/cd

#447 Fix examples regarding falcon_aph/aph
  molecule/falcon_configure/verify.yml
  plugins/modules/falconctl.py
  roles/falcon_configure/README.md
Labels: documentation, ok-to-test

#470 feat: add new falcon hosts dynamic inventory plugin
  README.md
  changelogs/fragments/falcon_hosts.yml
  plugins/README.md
  plugins/inventory/falcon_hosts.py
Labels: enhancement, minor_changes, new_release, feature_request

#472 docs: update role docs to be more expressive of what they do per os
  README.md
  SUPPORT.md
  roles/falcon_configure/README.md
  roles/falcon_install/README.md
Labels: documentation

#473 fix(host_hide): allow api limit to be managed in module seamlessly
  changelogs/fragments/host_hide_update.yml
  plugins/modules/host_hide.py
Labels: bugfixes

#474 Support for hostname templating
  changelogs/fragments/pr-474.yml
  plugins/inventory/falcon_hosts.py
Labels: bugfixes, enhancement, inventory

#475 Parameter templating
  plugins/inventory/falcon_hosts.py
Labels: enhancement, inventory

#478 Bump 4.3.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/falcon_hosts.yml
  changelogs/fragments/host_hide_update.yml
  changelogs/fragments/pr-474.yml
  galaxy.yml
Labels: new_release
