Repository CrowdStrike/ansible_collection_falcon, pull requests merged in 2024-09, with the labels that each got.

#552 feat(eda): add ability to start stream from the latest event
  changelogs/fragments/eda-updates.yml
  docs/crowdstrike.falcon.eventstream.md
  extensions/eda/plugins/event_source/eventstream.py
  tox.ini
Labels: bugfixes, minor_changes, eda

#553 fix(eda): make offset optional for nonetype
  extensions/eda/plugins/event_source/eventstream.py
Labels: bugfixes, eda

#554 docs(fctl_child_cid_info): correct group to global
  plugins/modules/fctl_child_cid_info.py
Labels: documentation

#557 feat(kernel_support_info): adds automatic pagination support
  changelogs/fragments/paginate-kernel-support-info.yml
  plugins/doc_fragments/info.py
  plugins/module_utils/falconpy_utils.py
  plugins/modules/kernel_support_info.py
Labels: minor_changes

#558 feat(info modules): enhance pagination and remove limits
  changelogs/fragments/info-updates.yml
  plugins/module_utils/falconpy_utils.py
  plugins/modules/kernel_support_info.py
  plugins/modules/sensor_download_info.py
  plugins/modules/sensor_update_policy_info.py
Labels: minor_changes

#560 docs(inventory): add api scopes to dynamic inventories
  plugins/inventory/falcon_discover.py
  plugins/inventory/falcon_hosts.py
Labels: documentation

#561 feat: add toggle for become on windows
  changelogs/fragments/toggle-win-become.yml
  roles/falcon_configure/README.md
  roles/falcon_configure/defaults/main.yml
  roles/falcon_configure/tasks/main.yml
  roles/falcon_install/README.md
  roles/falcon_install/defaults/main.yml
  roles/falcon_install/tasks/main.yml
  roles/falcon_uninstall/README.md
  roles/falcon_uninstall/defaults/main.yml
  roles/falcon_uninstall/tasks/main.yml
  roles/falcon_uninstall/tasks/remove_host_pretasks.yml
Labels: ok-to-test, minor_changes

#562 Bump 4.6.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/duplicate_hosts.yml
  changelogs/fragments/eda-updates.yml
  changelogs/fragments/info-updates.yml
  changelogs/fragments/paginate-kernel-support-info.yml
  changelogs/fragments/toggle-win-become.yml
  galaxy.yml
Labels: new_release

#565 fix(falcon_configure): this task should only run when both are set
  changelogs/fragments/fix-truthy-564.yml
  roles/falcon_configure/tasks/configure.yml
Labels: bugfixes, ok-to-test
