Repository CrowdStrike/ansible_collection_falcon, pull requests merged in 2024-12, with the labels that each got.

#581 chore: fix typos
  changelogs/typos.yml
  molecule/falcon_configure/molecule.yml
  molecule/falcon_configure_remove_aid/molecule.yml
  molecule/falcon_install/molecule.yml
  molecule/falcon_install_allow_downgrade/molecule.yml
  molecule/falcon_install_policy/molecule.yml
  molecule/falcon_uninstall/molecule.yml
  plugins/inventory/falcon_hosts.py
  plugins/module_utils/falconpy_utils.py
  plugins/modules/falconctl.py
  plugins/modules/host_contain.py
  plugins/modules/host_hide.py
  plugins/modules/sensor_update_policy_info.py
  roles/falcon_install/defaults/main.yml
Labels: bugfixes

#582 chore: prefer host retention policies over hide_host
  README.md
  changelogs/fragments/prefer-host-retention-policies.yml
  molecule/falcon_uninstall/molecule.yml
  plugins/lookup/host_ids.py
  plugins/modules/host_hide.py
  roles/falcon_uninstall/README.md
  roles/falcon_uninstall/tasks/main.yml
Labels: bugfixes, documentation, ok-to-test

#584 fix(falcon_install): fixes issue with deleting sensor when running locally
  .gitignore
  changelogs/fragments/578-localhost-deletion.yml
  roles/falcon_install/tasks/api.yml
  roles/falcon_install/tasks/cleanup.yml
  roles/falcon_install/tasks/main.yml
Labels: bugfixes

#585 fix(falcon_configure): fixes issue with unwarranted bool (master image)
  changelogs/fragments/579-fix-image-prep.yml
  molecule/falcon_configure_remove_aid/verify.yml
  roles/falcon_configure/tasks/configure.yml
Labels: bugfixes, ok-to-test

#588 fix(falcon_install): improves error message when using falcon_sensor_version_decrement but not enough historical sensors are available
  changelogs/fragments/577-decrement.yml
  roles/falcon_install/tasks/api.yml
Labels: bugfixes

#586 fix(falcon_configure): control aid generation wait time and logic
  changelogs/fragments/583-aid-retry.yml
  roles/falcon_configure/README.md
  roles/falcon_configure/defaults/main.yml
  roles/falcon_configure/tasks/configure.yml
Labels: bugfixes
